### ISSUE TITLE
v1.0.0 Release

### ISSUE THREAD

**Issue by ffflick-gh** [Citronite/CitrineBot#2]
### 🎉 Citrine is finally close to a v0.1.0 public release!

# v1.0.0 TODOs:
- [ ] Launcher (#8)
- [ ] Logo should be finalized (#5)
- [ ] Finish the help command (#10)
- [x] Fix formatter bug (#7)
- [x] package-lock??? (#9)

**Comment by ffflick-gh** [comment]
Scratch that - v1 will be released when built-in chips are stabilized.
